// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/beta": {
    params: {};
  };
  "/approach": {
    params: {};
  };
  "/resources/linkedin-ads-strategy": {
    params: {};
  };
  "/resources/linkedin-audience-targeting": {
    params: {};
  };
  "/resources/linkedin-ad-creative": {
    params: {};
  };
  "/resources/linkedin-tracking-attribution": {
    params: {};
  };
  "/resources/linkedin-retargeting": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/beta" | "/approach" | "/resources/linkedin-ads-strategy" | "/resources/linkedin-audience-targeting" | "/resources/linkedin-ad-creative" | "/resources/linkedin-tracking-attribution" | "/resources/linkedin-retargeting" | "/pricing" | "/about" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/beta.tsx": {
    id: "routes/beta";
    page: "/beta";
  };
  "routes/approach.tsx": {
    id: "routes/approach";
    page: "/approach";
  };
  "routes/resources.linkedin-ads-strategy.tsx": {
    id: "routes/resources.linkedin-ads-strategy";
    page: "/resources/linkedin-ads-strategy";
  };
  "routes/resources.linkedin-audience-targeting.tsx": {
    id: "routes/resources.linkedin-audience-targeting";
    page: "/resources/linkedin-audience-targeting";
  };
  "routes/resources.linkedin-ad-creative.tsx": {
    id: "routes/resources.linkedin-ad-creative";
    page: "/resources/linkedin-ad-creative";
  };
  "routes/resources.linkedin-tracking-attribution.tsx": {
    id: "routes/resources.linkedin-tracking-attribution";
    page: "/resources/linkedin-tracking-attribution";
  };
  "routes/resources.linkedin-retargeting.tsx": {
    id: "routes/resources.linkedin-retargeting";
    page: "/resources/linkedin-retargeting";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/beta": typeof import("./app/routes/beta.tsx");
  "routes/approach": typeof import("./app/routes/approach.tsx");
  "routes/resources.linkedin-ads-strategy": typeof import("./app/routes/resources.linkedin-ads-strategy.tsx");
  "routes/resources.linkedin-audience-targeting": typeof import("./app/routes/resources.linkedin-audience-targeting.tsx");
  "routes/resources.linkedin-ad-creative": typeof import("./app/routes/resources.linkedin-ad-creative.tsx");
  "routes/resources.linkedin-tracking-attribution": typeof import("./app/routes/resources.linkedin-tracking-attribution.tsx");
  "routes/resources.linkedin-retargeting": typeof import("./app/routes/resources.linkedin-retargeting.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};